config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  def draw(routes_name)
    instance_eval(File.read(Rails.root.join("config/routes/#{routes_name}.rb")))
  end

  # tell devise that users management are under accounts path
  devise_for :users, path: 'accounts', :controllers => {:registrations => "public/registrations", :sessions => "sessions"}


  scope :module => 'public' do

    if Rails.env.development?
      get 'welcome/index'
      get "/search" => "professionals#index"
      get "/professionals/search" => "professionals#index"
      get "/professionals/:id" => "doctors#profile", as: :doctor_public_profile
      ## TODO, except for new
      authenticate :user do
        resources :appointments
        get "/profile" => "profile#index"
        get "/settings" => "settings#index"
      end
    else
      get '*' => redirect('/professional/welcome')
    end

    namespace :company do
      # common pages
      get "/" => 'pages#index'
      # contact
      match "/contact" => "contact#index", :as => 'contact_us', via: [:get, :post]
      # features
      match "/features" => "features#index", :as => 'features', via: [:get, :post]
      # product
      get "/product/:page" => "product#pages", :as => 'product_pages'

      # default
      get "/:page" => 'pages#pages', :as => 'pages'
    end

    get "/guide/:page" => "guide#pages", :as => 'guide_pages'

  end


  draw :api

  # professional

  namespace :professional do
    get '/welcome', to: 'welcome#index'
    get '/', to: redirect('professional/dashboard')

    authenticate :user do
      namespace :dashboard do
        get '/', to: 'dashboard#index'
        resources :appointments
        resources :professional_holidays, :path => "/holidays"
        scope as: :scheduler, path: :scheduler do
          post '/update', to: 'professional_availability#update'
          get '/', to: 'professional_availability#index'
        end
        resources :professional_configs, only: [:index, :update]
        get '/pending', to: 'dashboard#pending'
        post '/request-confirmation', to: 'dashboard#request_confirmation'
      end

      namespace :vault do
        resources :documents
        get '/', to: 'vault#index'
      end
    end

    # devise handling for doctor
    devise_scope :user do
      get 'account/new', to: 'account#new', as: 'new_registration'
      post 'account/create', to: 'account#create', as: 'registration'
      match "account/register-as-professional", to: 'account#register_as_professional', as: :register_as_professional, via: [:get, :post]
      authenticate :user do
        get 'profile', to: 'profile#index', as: :profile

        patch 'profile/info', to: 'profile#info', as: :profile_info
        patch 'profile/address', as: :profile_address


        # specialities
        #
        patch 'profile/specialities', as: :profile_specialities

        post 'profile/documents', as: :profile_documents
        post 'profile/update'


        # specialities
        #
        patch 'profile/security', as: :profile_security

        get 'profile/confirm-request-required-documents', to: 'profile#confirm_profile'
        post 'profile/confirm-request-required-documents', to: 'profile#confirm_profile_request'
      end
    end
  end


  authenticate :user do
    namespace 'admin', module: :admin do
      root 'dashboard#index'
      resources :professionals do
        get 'requests'
        member do
          post 'confirm-request'
          post 'decline-request'
          match 'block-account', via: [:get, :post]
          post 'unblock-account'
        end

      end
    end
  end



  if not Rails.env.development?
    root 'professional/welcome#index'
  else
    root 'public/welcome#index'
  end

  # settings
  #
  get "/status/admin-not-found" => "app_status#admin_not_found"


  constraints Constraints::MonitoringWhiteListConstraint.new do
    mount Sidekiq::Web => '/sidekiq'
  end

end

app/views/partials/_calendar.html.erb
<% unless intervals.nil? %>
  <!-- build events collection -->
  <% events = intervals.map {|entry| {:id => entry[:id], :range => entry[:range], :color => gen_event_color(entry)}} %>
<% end %>
<div class="columns calendar is-multiline">
  <% range.each do |entry| %>
    <div class="column is-4 has-text-centered">
      <% previous_month_end = entry.ago(1.month).end_of_month %>
      <% row = 0 %>
      <table class="month">
        <thead>
        <tr>
          <td colspan="7">
            <div class="month-name"> <%= entry.strftime("%B %Y") %></div>
          </td>
        </tr>
        <tr class="week">
          <% Date::ABBR_DAYNAMES.rotate.each_with_index do |day, index| %>
            <td class="day-week">
              <%= t('date.abbr_day_names')[index].capitalize %>
          <% end %>
        </tr>
        </thead>
        <tbody>
        <!-- if it not start with monday -->
        <% if entry.beginning_of_month.wday != 1 %>
          <tr>
            <% (previous_month_end.day - (previous_month_end.wday - 1)..previous_month_end.day).each do |day| %>
              <td class="out-of-month">
                <% row = row + 1 %>
              </td>
            <% end %>
        <% end %>

        <% (entry.beginning_of_month.day..entry.end_of_month.day).each do |day| %>
          <!-- last month ended at 6-->
          <% if row % 7 == 0 %>
            <tr>
          <% end %>
          <td>
            <%= day %>
            <% unless events.nil? %>
              <% current_day = DateTime.new(entry.year, entry.mon, day) %>
              <% if in_holiday?(current_day, events) %>
                <% get_classes(current_day, events).each do |e| %>
                  <div class="in-event" style="background:#<%= e[:color] %>"></div>
                <% end %>
              <% end %>
            <% end %>
            <% row = row + 1 %>
          </td>
          <!-- if we end the current week -->
          <% if row % 7 == 0 %>
            </tr>
            <tr>
          <% end %>
        <% end %>
        </tr>
        </tbody>
      </table>
    </div>

  <% end %>
</div>

app/views/partials/_contact.html.erb
<%= form_tag(company_contact_us_path, local: true) do %>
  <div class="section">
    <div class="container">
      <!-- Title -->
      <div class="section-title-wrapper has-text-centered">
        <h3 class="subtitle is-2"><%= t('contact.subject') %></h3>
      </div>
      <div class="columns">
        <div class="column is-6">
          <!-- Contact form -->
          <div class="contact-form">
            <form>
              <div class="columns is-multiline">
                <div class="column is-6">
                  <div class="control">
                    <label><%= t('contact.form.first_name') %></label>
                    <%= text_field(:contact, :name, {class: "input is-medium"}) %>
                  </div>
                </div>
                <div class="column is-6">
                  <div class="control">
                    <label><%= t('contact.form.last_name') %></label>
                    <input class="input is-medium" type="text">
                  </div>
                </div>
                <div class="column is-6">
                  <div class="control">
                    <label><%= t('contact.form.email') %> *</label>
                    <%= text_field(:contact, :email, {class: "input is-medium"}) %>
                  </div>
                </div>
                <div class="column is-6">
                  <div class="control">
                    <label><%= t('contact.form.organisation') %> </label>
                    <%= text_field(:contact, :organisation, {class: "input is-medium"}) %>
                  </div>
                </div>
                <div class="column is-12">
                  <div class="control">
                    <label><%= t('contact.form.message') %> *</label>
                    <%= text_area(:contact, :body, rows: 4, class: "textarea") %>
                  </div>
                </div>
              </div>
              <div class="submit-wrapper">
                <%= submit_tag t('welcome.contact_us'), :class => "button bg-primary-5 has-shadow is-margin-auto" %>

              </div>
            </form>
          </div>
        </div>
        <div class="column is-5 is-offset-1">
          <!-- Contact info tabs -->
          <div class="contact-toggler">
            <ul class="tabbed-links">
              <li data-contact="contact_by_email" class="is-active">Email</li>
              <li data-contact="contact_by_location">Location</li>
            </ul>
            <div class="contact-blocks">
              <!-- Tab content -->
              <div id="contact_by_email" class="contact-block animated preFadeInUp fadeInUp ">
                <div class="contact-icon">
                  <% cache "icon-mail" do %>
                    <%= render_icon("icon-mail") %>
                  <% end %>
                </div>
                <div class="contact-info">
                  <a href="mailto:fathallah.houssem@gmail.com">Contactez nous</a>
                </div>
              </div>
              <!-- Tab content -->
              <div id="contact_by_location" class="contact-block animated preFadeInUp fadeInUp is-hidden">
                <div class="contact-icon">
                  <% cache "icon-location-pin" do %>
                    <%= render_icon("icon-location-pin") %>
                  <% end %>
                </div>
                <div class="contact-info">
                  <span></span>
                  <span> Sousse, Tunisie </span>
                </div>
              </div>
            </div>
            <!-- Illustration -->
            <img style="width: 400px" src="<%= asset_path('illustrations/professional/undraw_best_place_r685.svg') %>" alt="">
          </div>
        </div>
      </div>
    </div>
<% end %>

app/views/partials/_footer_brand.html.erb
© <%= Date.today.strftime("%Y") %> Bloosa , a <a href=" https://www.380squares.xyz/"> 380Squares </a> product

app/views/partials/_footer_in.html.erb
<style>
  .footer-in .footer-in__links a {
    display: inline-block;
    font-size: 12px;
    margin: .25rem .5rem ;
  }

  .footer-in {
    padding: 0;
  }
    .footer-in .brand{
      font-size: 14px;
    }
</style>
<footer class="footer-in footer">
  <div class="has-text-centered footer-in__links">

    <%= link_to(company_pages_path('security-and-data')) do %>
      <%= t('footer.guide_links.security_and_data_protection') %>
    <% end %>
    <%= link_to(company_features_path) do %>
      <%= t('footer.product_links.request_features') %>
    <% end %>
    <%= link_to(company_pages_path('contact')) do %>
      <%= t('Contact') %>
    <% end %>
    <%= link_to(company_pages_path('roadmap')) do %>
      <%= t('footer.product_links.our_roadmap') %>
    <% end %>
    <%= link_to(guide_pages_path('professional')) do %>
      <%= t('Guide') %>
    <% end %>
    <%= link_to(company_pages_path('faq')) do %>
      <%= t('FAQ') %>
    <% end %>

    <%= link_to(company_pages_path('team')) do %>
      <%= t('Team') %>
    <% end %>
  </div>
  <div class="has-text-centered brand">
    <%= render 'partials/footer_brand' %>
  </div>

</footer>
<!--/footer-->

app/views/partials/_header.html.erb
<% unless user_signed_in? %>
  <%= render 'partials/navbar_out', clone: false %>
  <%= render 'partials/navbar_out', clone: true %>
<% end %>

app/views/partials/_header_in.html.erb
<nav class="navbar main-navbar is-transparent no-shadow"
     role="navigation" aria-label="main navigation">
  <div class="container">
    <div class="navbar-brand">
      <a href="/" class="navbar-item">
        Bloosa
      </a>
    </div>

    <div id="navbar-menu" class="navbar-menu is-static">
      <div class="navbar-end">
        <% if current_user.is_admin? %>
          <%= link_to(admin_root_path, {:class => "navbar-item"}) do %>
            Admin Dashboard
          <% end %>
        <% end %>
        <% if current_user.is_doctor? %>
          <%= link_to(professional_dashboard_path, {:class => "navbar-item"}) do %>
            Doctor Dashboard
          <% end %>
        <% end %>
        <%= link_to(appointments_path, {:class => "navbar-item"}) do %>
          <%= t('appointments') %>
        <% end %>
        <div class="navbar-item has-dropdown is-hoverable">
          <a class="navbar-link">
            <%= render :partial => 'partials/icon', :locals => {:icon => 'icon-dots-horizontal'} %>
          </a>

          <div class="navbar-dropdown  is-right">

            <%= link_to(appointments_path, :class => "navbar-item") do %>
              <%= t('app.my_appointments') %>
            <% end %>
            <hr class="navbar-divider">

            <%= link_to(company_pages_path('security-and-data'), :class => "navbar-item") do %>
              <%= t('footer.guide_links.security_and_data_protection') %>
            <% end %>
            <%= link_to(company_pages_path('contact'), :class => "navbar-item") do %>
              <%= t('Contact') %>
            <% end %>
            <%= link_to(company_pages_path('team'), :class => "navbar-item") do %>
              <%= t('Team') %>
            <% end %>
            <%= link_to(company_pages_path('documentation'), :class => "navbar-item") do %>
              <%= t('Documentation') %>
            <% end %>
            <%= link_to(company_pages_path('faq'), :class => "navbar-item") do %>
              <%= t('FAQ') %>
            <% end %>
            <hr class="navbar-divider">

            <%= link_to(destroy_user_session_path, :method => :delete, :class => "navbar-item") do %>
              Log out
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/partials/_icon.html.erb
<svg viewBox="0 0 24 24" class="app-icon <%= defined?(svgClass) ? svgClass: '' %>">
  <use xlink:href="<%= '#' + icon %>" class="<%= defined?(cssClass) ? cssClass : 'icon' %>"></use>
</svg>

app/views/partials/_logo.html.erb
  bloosa

app/views/partials/_map_scripts.html.erb
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.3/dist/leaflet.css"
      integrity="sha512-Rksm5RenBEKSKFjgI3a41vrjkw4EVPlJ3+OiI65vTjIdo9brlAacEuKOiQ5OFh7cOI1bkDwLqdLw3Zg0cRJAAQ=="
      crossorigin=""/>
<script src="https://unpkg.com/leaflet@1.3.3/dist/leaflet.js"
        integrity="sha512-tAGcCfR4Sc5ZP5ZoVz0quoZDYX5aCtEm/eu1KhSLj2c9eFrylXZknQYmxUssFaVJKvvc0dJQixhGjG2yXWiV9Q=="
        crossorigin=""></script>

app/views/partials/_navbar_out.html.erb
<nav class="navbar main-navbar is-transparent no-shadow"
     <% if clone %>
     id="navbar-clone"
     <% end %>
     role="navigation" aria-label="main navigation">
  <div class="container">
    <div class="navbar-brand">
      <a href="<%= root_path %>" title="Findoctor" class="navbar-item">
        Bloosa
      </a>

    </div>

    <div id="navbar-menu" class="navbar-menu is-static">


      <div class="navbar-end">

        <%= link_to professional_welcome_path, class: 'navbar-item' do %>
          <span>
              <%= t('welcome.i_am_doctor') %>
          </span>
        <% end %>
        <% if Rails.env.development? %>

          <%= link_to new_user_session_path, class: 'navbar-item' do %>
          <span class="bg-primary-5 button rounded">
              <%= t('account.sign_in') %>
          </span>
          <% end %>

          <%= link_to new_user_registration_path, class: 'navbar-item' do %>
         <span class="bg-support-red-6 button rounded">
               <%= t('Sign up') %>
                    </span>

          <% end %>
        <% else %>
          <%= link_to company_pages_path('contact'), class: 'navbar-item' do %>
         <span class="bg-primary-5 button rounded">
               <%= t('footer.guide_links.contact') %>
                    </span>

          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</nav>

app/views/partials/_preloader.html.erb
<!--
<div id="preloader">
  <div id="status"></div>
</div>-->

app/views/partials/_scripts.html.erb
<script>
    window.appConfig = {
        baseApi: '/api/v1/',
        locale: '<%= I18n.locale %>'
    };
</script>
<script async src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
<script async src="https://unpkg.com/scrollreveal"></script>
<script async src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
<script async src="https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js"></script>

app/views/partials/_wip.html.erb
<span>Content under construction, please do not hesitate to  <%= link_to(company_pages_path('contact')) do %>
              contact us
            <% end %></span>