config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  def draw(routes_name)
    instance_eval(File.read(Rails.root.join("config/routes/#{routes_name}.rb")))
  end

  # tell devise that users management are under accounts path
  devise_for :users, path: 'accounts', :controllers => {:registrations => "public/registrations", :sessions => "sessions"}


  scope :module => 'public' do

    if Rails.env.development?
      get 'welcome/index'
      get "/search" => "professionals#index"
      get "/professionals/search" => "professionals#index"
      get "/professionals/:id" => "doctors#profile", as: :doctor_public_profile
      ## TODO, except for new
      authenticate :user do
        resources :appointments
        get "/profile" => "profile#index"
        get "/settings" => "settings#index"
      end
    else
      get '*' => redirect('/professional/welcome')
    end

    namespace :company do
      # common pages
      get "/" => 'pages#index'
      # contact
      match "/contact" => "contact#index", :as => 'contact_us', via: [:get, :post]
      # features
      match "/features" => "features#index", :as => 'features', via: [:get, :post]
      # product
      get "/product/:page" => "product#pages", :as => 'product_pages'

      # default
      get "/:page" => 'pages#pages', :as => 'pages'
    end

    get "/guide/:page" => "guide#pages", :as => 'guide_pages'

  end


  draw :api

  # professional

  namespace :professional do
    get '/welcome', to: 'welcome#index'
    get '/', to: redirect('professional/dashboard')

    authenticate :user do
      namespace :dashboard do
        get '/', to: 'dashboard#index'
        resources :appointments
        resources :professional_holidays, :path => "/holidays"
        scope as: :scheduler, path: :scheduler do
          post '/update', to: 'professional_availability#update'
          get '/', to: 'professional_availability#index'
        end
        resources :professional_configs, only: [:index, :update]
        get '/pending', to: 'dashboard#pending'
        post '/request-confirmation', to: 'dashboard#request_confirmation'
      end

      namespace :vault do
        resources :documents
        get '/', to: 'vault#index'
      end
    end

    # devise handling for doctor
    devise_scope :user do
      get 'account/new', to: 'account#new', as: 'new_registration'
      post 'account/create', to: 'account#create', as: 'registration'
      match "account/register-as-professional", to: 'account#register_as_professional', as: :register_as_professional, via: [:get, :post]
      authenticate :user do
        get 'profile', to: 'profile#index', as: :profile

        patch 'profile/info', to: 'profile#info', as: :profile_info
        patch 'profile/address', as: :profile_address


        # specialities
        #
        patch 'profile/specialities', as: :profile_specialities

        post 'profile/documents', as: :profile_documents
        post 'profile/update'


        # specialities
        #
        patch 'profile/security', as: :profile_security

        get 'profile/confirm-request-required-documents', to: 'profile#confirm_profile'
        post 'profile/confirm-request-required-documents', to: 'profile#confirm_profile_request'
      end
    end
  end


  authenticate :user do
    namespace 'admin', module: :admin do
      root 'dashboard#index'
      resources :professionals do
        get 'requests'
        member do
          post 'confirm-request'
          post 'decline-request'
          match 'block-account', via: [:get, :post]
          post 'unblock-account'
        end

      end
    end
  end



  if not Rails.env.development?
    root 'professional/welcome#index'
  else
    root 'public/welcome#index'
  end

  # settings
  #
  get "/status/admin-not-found" => "app_status#admin_not_found"


  constraints Constraints::MonitoringWhiteListConstraint.new do
    mount Sidekiq::Web => '/sidekiq'
  end

end

app/controllers/admin/professionals_controller.rb
class Admin::ProfessionalsController < Admin::AdminController

  before_action :set_doctor_profile, :only => [:show, :confirm_request, :decline_request, :block_account], raise: false

  def index
    query = request.query_parameters
    @query = query[:q]
    specialities_ids = []
    if @query.present?
      specialities_ids = Speciality.find_by_field_query(@query).map(&:id)
    end

    @doctors = DoctorProfile
                   .eager_load(:doctor_profile_status, :specialities, :user => [:user_profile])


    ###
    # .joins(:doctor_profile_status)
    #                    .where(doctor_profile_statuses: {status: 'REQUEST'})
    #
    #
    if @query.present?
      @doctors = DoctorProfile
                     .joins(:user => :user_profile) #TODO, fix sanitzation
                     .where("user_profiles.name like '%#{@query}%'")
                     .joins(:specialities)
                     .uniq
      "" ".where(:doctors_specialities => {:speciality_id => specialities_ids})
                     " ""
    end
  end

  def show

  end

  # get all requests for doctor profile
  def requests
    ids = DoctorProfileStatus.where(status: PROFILE_STATUES.request).map(&:id)
    @profiles = DoctorProfile.where(confirmation_status_id: ids).eager_load(:user, :doctor_profile_status, :specialities)
  end


  def block_account
    @professional_block_account_history = ProfessionalBlockAccountHistory.new
    professional_id = params[:id]
    user = User.find(professional_id)
    unless user.nil?
      if user.is_professional?
        @user = user
        # TO, check for existing
        @professional_block_account_history.professional_id = professional_id
        if request.post?
          professional_block = ProfessionalBlockAccountHistory.new(block_account_params)
          professional_block.blocked_by_id = current_user.id
          professional_block.professional_id = professional_id
          if professional_block.save
            user.block_professional_account()
            AdminMailer.block_professional_account(user.id, professional_block.blocking_reason).deliver_now!
            DoctorMailer.account_blocked_notification(user.id, professional_block.blocking_reason).deliver_now!
            flash[:notice] = I18n.t('admin.flash.account_blocked_success')
            redirect_to admin_professionals_path
          else
            @errors = professional_block.errors
          end
        end
      else
        flash[:notice] = I18n.t('This use is not a professional')
        redirect_to admin_professionals_path
      end
    end

  end

  def unblock_account
    redirect_to admin_professionals_path
  end

  # get all requests for doctor profile
  def confirm_request
    message = params[:message]
    @doctor_profile.doctor_profile_status =
        DoctorMailer.send_confirmation_request(@doctor_profile.user_id, message).deliver_later
  end

  def decline_request
    message = params[:message]
    #TODO
    # DoctorMailer.send_decline_request(@doctor_profile.user_id, message).deliver_later
  end

  protected

  def set_doctor_profile
    @doctor_profile = DoctorProfile.find_by_user_id(params[:id])
    # TODO, rais if not exists
  end


  def block_account_params
    params.fetch(:professional_block_account_history, {}).permit([:user_id, :blocking_reason])
  end
end

app/controllers/api/v1/mobile/accounts_controller.rb
module Api
  module V1
    module Mobile
      class AccountsController < BaseController
        def account
          render :json => {:data => 'hello'}
        end
      end
    end
  end
end

app/controllers/api/v1/professional/geo_controller.rb
module Api
  module V1
    module Professional
      class GeoController < BaseController
        #caches_action :index, :layout => false
        def reverse
          results = Geocoder.search("#{params[:lat]}, #{params[:lng]}")
          render :json => {:list => results}
        end

        #caches_action :index, :layout => false
        def index
          cities
        end
      end
    end
  end
end

app/controllers/api/v1/professionals_controller.rb
module Api
  module V1
    class ProfessionalsController < BaseController
      include SearchHelper

      def search
        unless params[:location].nil?
          city = City.find_by_id(params[:location])
        end
        @doctors = User
                       .select("users.id, users.email")
                       .eager_load(:user_profile, doctor_profile: {specialities: :speciality})
                       .joins(:professional_holidays)
                       .where("DATE '#{Date.new(2019, 8, 20)}' NOT BETWEEN professional_holidays.start_at AND professional_holidays.end_at")
                       .joins(:user_profile)
                       .joins(:doctor_profile)
                       .where({doctor_profiles: {is_confirmed: true}})
                       .where(doctor_profiles_close_to_query(35.796003, 10.635681, 4000))


        if params[:specialities]
          @doctors = @doctors
                         .joins(:doctors_specialities)
                         .where(:doctors_specialities => {:speciality_id => params[:specialities]})

        end

        @doctors = @doctors.uniq

        "" "
        .select(:id)
                       .eager_load(:doctor_profile)
                       .joins(:doctor_profile)
                       .where({doctor_profiles: {is_confirmed: true}})

                       .joins(:specialities)
                       .where(:doctors_specialities => {:speciality_id => specialities_ids})
                       .uniq
" ""
        render :json => {data: @doctors.as_json(only: [:id],
                                                include: {
                                                    doctor_profile: {
                                                        only: [:full_address, :latitude, :longitude, :address],
                                                        include: {
                                                            specialities: {
                                                                only: [],
                                                                include: {
                                                                    speciality: {
                                                                        only: [:id, :en_fr, :en_ar]
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    },
                                                    user_profile: {only: [:name, :last_name, :title]},
                                                })}
      end


      def recommended
        @doctors = User.all
        render :json => {:data => @doctors}
      end


      def profile
        @doctors = DoctorProfile.all
        render :json => {:data => @doctors}
      end

      def vote

      end

    end
  end
end

app/controllers/professional/account_controller.rb
class Professional::AccountController < Devise::RegistrationsController
  include ProfessionalHelper

  #https://stackoverflow.com/questions/41266207/before-process-action-callback-authenticate-user-has-not-been-defined#41266746
  skip_before_action :is_doctor?, :only => [:create, :register_as_professional], raise: false
  skip_before_action :idle_profile_status?, :only => [:create, :register_as_professional], raise: false

  before_action :configure_permitted_parameters, if: :devise_controller?

  def new
    super do
      resource.build_user_profile
      resource.build_doctor_profile
    end
  end

  def create
    super do
      if resource.persisted?
        send_request_doctor_mail(resource)
      end
    end
  end

  # A user already create an account but
  def register_as_professional
    if current_user
      if request.method === "POST"
        @profile = current_user.create_doctor_profile!()
        puts (@profile)
        ## @profile TODO add
        if @profile.save!
          flash[:success] = t("Request for becoming doctor is confirmed")
          # Tell the UserMailer to send a welcome email after save
          send_request_doctor_mail(current_user)
          redirect_to :doctor_profile
        else
          flash[:error] = t('Something went wrong !')
        end
      else
        # if get, build profile
        @profile = current_user.build_doctor_profile
      end
    else
      redirect_to :doctor_new_registration
    end

  end

  protected

  def after_sign_up_path_for(resource)
    :doctor_profile_update
  end

  def send_request_doctor_mail (user)
    AdminMailer.request_for_doctor_account(user.id).deliver_later
    UserMailer.request_doctor_profile(user.id).deliver_later
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :password, :password_confirmation,
                                                       {user_profile_attributes: [:name, :last_name, :birthday, :address, :zip_code]},
                                                       {doctor_profile_attributes: [:street, :latitude, :longitude, :full_address, :zip_code]}])
  end

end

app/controllers/professional/dashboard/appointments_controller.rb
class Professional::Dashboard::AppointmentsController < Professional::ProfessionalController
  def index

    @consultations = current_user.consultations
    @month = Date.current.beginning_of_month
    unless params[:month].nil?
      begin
        @month = Date.strptime(params[:month], "%Y-%m-%d")
      rescue
        nil
      end
    end

  end

  # confirm appointment
  # Check for disponiblity
  # disable disponibilites
  def confirm

  end
end

app/controllers/professional/dashboard/dashboard_controller.rb
class Professional::Dashboard::DashboardController < Professional::ProfessionalController
  skip_before_action :waiting_confirmation_status?, :only => [:pending, :request_confirmation]

  def index
    render 'professional/dashboard/index'
  end

  def pending
    render 'professional/dashboard/pending', :layout => false
  end

  def request_confirmation
    user_id = current_user.id
    AdminMailer.request_for_doctor_account_confirmation(user_id).deliver_now
    UserMailer.request_doctor_profile_confirmation(user_id).deliver_later
  end
end

app/controllers/professional/dashboard/professional_configs_controller.rb
class Professional::Dashboard::ProfessionalConfigsController < Professional::ProfessionalController

  before_action :set_professional_config, only: [:index, :update]


  def index
    render 'update'
  end

  # POST /professional_configs
  def update

    @professional_config.update(update_params.except(:user))

    user_params = update_params[:user]

    current_user.update!(user_params)

    if current_user.phone_number_changed?
      current_user.two_factor_via_confirmed = false
    end

    redirect_to professional_dashboard_professional_configs_path
  end


  private



  # Never trust parameters from the scary internet, only allow the white list through.
  def update_params

  end

end

app/controllers/professional/professional_controller.rb
class Professional::ProfessionalController < ApplicationController
  include ProfessionalHelper
  before_action :is_doctor?
  before_action :idle_profile_status?
  before_action :waiting_confirmation_status?
  layout 'doctor'
end

app/controllers/professional/vault/documents_controller.rb
class  Professional::Vault::DocumentsController < Professional::ProfessionalController

  def index

  end

end

app/controllers/professional/vault/vault_controller.rb
class Professional::Vault::VaultController < Professional::ProfessionalController
  def index
    render 'professional/vault/index'
  end

  private

  def profile_request_params
    params.require(:doctor_profile).permit(files: [], speciality_ids: [])
  end


  def update_params
    params.require(:doctor_profile).permit(:city, :avatar, speciality_ids: [])
  end
end

app/helpers/professional/account_helper.rb
module Professional::AccountHelper
  PROFILE_STATUES = {
      :request => 'REQUEST'
  }
end

app/helpers/professional/appointments_helper.rb
module Professional::AppointmentsHelper

  def appointments_future_count
    Appointment.where({:doctor_id => current_user.id}).where('time > ?', Time.now).count()
  end

end

app/helpers/professional/dashboard_helper.rb
module Professional::DashboardHelper
end

app/helpers/professional/doctor_availability_helper.rb
module Professional::DoctorAvailabilityHelper

  def should_configure_scheduler?
    current_user.doctor_availabilities.count == 0
  end

  def should_configure_system?
    current_user.professional_config.nil?
  end

end

app/helpers/professional_helper.rb
module ProfessionalHelper
  def is_doctor?
    unless current_user&.is_doctor?
      redirect_to doctor_register_as_professional_path
    end
  end

  def idle_profile_status?
    unless current_user&.doctor_profile&.is_confirmed?
      if current_user.doctor_profile.idle_profile_status?
        redirect_to doctor_profile_confirm_request_required_documents_path
      end
    end
  end
  # check if doctor is waiting request
  def waiting_confirmation_status?
    unless current_user&.doctor_profile&.is_confirmed?
      if current_user.doctor_profile.waiting_confirmation_status?
        redirect_to doctor_dashboard_pending_path
      end
    end
  end

  def can_proceed_view_if_not_confirmed
    controller = controller_name
    (controller == 'profile_controller' && action_name == "confirm_profile") || current_user.doctor_profile.is_confirmed
  end

  def set_request_variant
    request.format = 'html' if request.format == 'mobile'
  end
end

app/views/professional/account/_doctor_profile_form.html.erb
<%= f.fields_for :doctor_profile do |doctor_form| %>

  <div class="form-group">
    <label><%= t('Zip Code') %>*</label>
    <%= doctor_form.text_field :zip_code,
                               required: true,
                               placeholder: t("Zip Code"),
                               label: false,
                               class: 'form-control' %>
    <label><%= t('Full Address') %>*</label>
    <%= doctor_form.text_field :full_address,
                               required: true,
                               placeholder: t('Full Address'),
                               label: false,
                               class: 'form-control' %>
  </div>

  <div class="form-group">
    <label><%= t('Street') %>*</label>
    <%= doctor_form.text_field :street,
                               required: true,
                               placeholder: t("Street"),
                               label: false,
                               class: 'form-control' %>
  </div>

  <div class="form-group">
    <label><%= t('Country') %>*</label>
    <%= doctor_form.select(:country_id, options_for_select(Country.all.map {|s| [s.name, s.id]}), {}, {:class => 'form-control'}) %>
  </div>

  <div class="form-group">
    <label><%= t('City') %>*</label>
    <%= doctor_form.select(:city_id, options_for_select(City.all.map {|s| [s.name, s.id]}), {}, {:class => 'form-control'}) %>
    </div>

<% end %>

app/views/professional/account/become_a_doctor.html.erb
<div class="bg_color_2">
  <div class="container margin_60_35">
    <div id="login-2">
      <h2><%= t('Sign up') %></h2>
      <%= simple_form_for(@profile, url: doctor_register_as_professional_path) do |f| %>
        <%= render "doctor/account/doctor_profile_form", f: f %>
        <div class="form-group text-center add_top_30">
          <%= f.button :submit, "Sign up", class: 'btn_1' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/professional/account/confirm.html.erb
<h2>Sign up</h2>

<%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :email, required: true, autofocus: true %>
    <%= f.input :password, required: true, hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length) %>
    <%= f.input :password_confirmation, required: true %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Sign up" %>
  </div>
<% end %>

<%= render "devise/shared/links" %>

<div id="hero_register">
  <div class="container margin_120_95">
    <div class="row">
      <div class="col-lg-6">
        <h1>It's time to find you!</h1>
        <p class="lead">Te pri adhuc simul. No eros errem mea. Diam mandamus has ad. Invenire senserit ad has, has ei
          quis iudico, ad mei nonumes periculis.</p>
        <div class="box_feat_2">
          <i class="pe-7s-map-2"></i>
          <h3>Let patients to Find you!</h3>
          <p>Ut nam graece accumsan cotidieque. Has voluptua vivendum accusamus cu. Ut per assueverit temporibus
            dissentiet.</p>
        </div>
        <div class="box_feat_2">
          <i class="pe-7s-date"></i>
          <h3>Easly manage Bookings</h3>
          <p>Has voluptua vivendum accusamus cu. Ut per assueverit temporibus dissentiet. Eum no atqui putant
            democritum, velit nusquam sententiae vis no.</p>
        </div>
        <div class="box_feat_2">
          <i class="pe-7s-phone"></i>
          <h3>Instantly via Mobile</h3>
          <p>Eos eu epicuri eleifend suavitate, te primis placerat suavitate his. Nam ut dico intellegat reprehendunt,
            everti audiam diceret in pri, id has clita consequat suscipiantur.</p>
        </div>
      </div>
      <!-- /col -->
      <div class="col-lg-5 ml-auto">
        <div class="box_form">
          <form>
            <div class="row">
              <div class="col-md-6 ">
                <div class="form-group">
                  <input type="text" class="form-control" placeholder="Name">
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-group">
                  <input type="text" class="form-control" placeholder="Last Name">
                </div>
              </div>
            </div>
            <!-- /row -->
            <div class="row">
              <div class="col-lg-12">
                <div class="form-group">
                  <input type="text" class="form-control" placeholder="Specialization">
                </div>
              </div>
            </div>
            <!-- /row -->
            <div class="row">
              <div class="col-md-6">
                <div class="form-group">
                  <input type="text" class="form-control" placeholder="City">
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-group">
                  <select class="form-control">
                    <option value="">Country</option>
                  </select>
                </div>
              </div>
            </div>
            <!-- /row -->
            <div class="row">
              <div class="col-md-6">
                <div class="form-group">
                  <input type="text" class="form-control" placeholder="Mobile Phone">
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-group">
                  <input type="text" class="form-control" placeholder="Office Phone">
                </div>
              </div>
            </div>
            <!-- /row -->
            <div class="row">
              <div class="col-lg-12">
                <div class="form-group">
                  <input type="email" class="form-control" placeholder="Email Address">
                </div>
              </div>
            </div>
            <!-- /row -->
            <p class="text-center add_top_30"><input type="submit" class="btn_1" value="Submit"></p>
            <div class="text-center">
              <small>Ut nam graece accumsan cotidieque. Has voluptua vivendum accusamus cu. Ut per assueverit temporibus
                dissentiet.
              </small>
            </div>
          </form>
        </div>
        <!-- /box_form -->
      </div>
      <!-- /col -->
    </div>
    <!-- /row -->
  </div>
  <!-- /container -->
</div>

app/views/professional/account/new.html.erb
<div id="hero_register">
  <div class="container margin_120_95">
    <div class="row">
      <div class="col-lg-6">
        <h1>It's time to find you!</h1>
        <div class="box_feat_2">
          <i class="pe-7s-shield"></i>
          <h3>Security </h3>
          <p>Eos eu epicuri eleifend suavitate, te primis placerat suavitate his. Nam ut dico intellegat reprehendunt,
            everti audiam diceret in pri, id has clita consequat suscipiantur.</p>
        </div>
        <div class="box_feat_2">
          <i class="pe-7s-shield"></i>
          <h3>Security </h3>
          <p>Eos eu epicuri eleifend suavitate, te primis placerat suavitate his. Nam ut dico intellegat reprehendunt,
            everti audiam diceret in pri, id has clita consequat suscipiantur.</p>
        </div>
      </div>
      <!-- /col -->
      <div>
        <div class="box_form">
          <%= simple_form_for(resource, as: resource_name, url: professional_registration_path) do |f| %>
            <%= f.error_notification %>
            <%= f.fields_for :user_profile do |profile_form| %>
              <div class="row">
                <div class="fields">
                  <div>
                    <label class="label"><%= t('Name ') %></label>
                    <%= profile_form.text_field(:name, {:placeholder => "First Name", :autofocus => true, :class => 'form-control'}) %>
                  </div>
                </div>
                <div>
                  <div class="field">
                    <label class="label"><%= t('Last name ') %></label>
                    <%= profile_form.text_field :last_name, autofocus: true, :placeholder => "First Name", class: 'form-control' %>
                  </div>
                </div>
              </div>


              <div class="form-group">
                <label><%= t('Email') %></label>
                <%= f.input :email, autofocus: true, placeholder: t("Your email address"), label: false, :input_html => {class: 'form-control'} %>
              </div>
              <div class="form-group">
                <label><%= t('Password') %></label>
                <%= f.input :password, required: true, hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length), placeholder: "Your password", label: false, :input_html => {class: 'form-control'} %>
              </div>
              <div class="form-group">
                <label><%= t('Confirm password') %></label>
                <%= f.input :password_confirmation, required: true, placeholder: t("Confirm password"), label: false, :input_html => {class: 'form-control'} %>
              </div>
              <div class="form-group">
                <label><%= t('doctor.form.Address') %>*</label>
                <%= profile_form.text_field :address, required: true, placeholder: t('doctor.form.Address'), label: false, class: 'form-control' %>
              </div>
              <div class="form-group">
                <label><%= t("doctor.form.Zip code") %>*</label>
                <%= profile_form.text_field :zip_code, required: true, placeholder: t("doctor.form.Zip code"), label: false, class: 'form-control' %>
              </div>

              <div class="form-group">
                <label><%= t("doctor.form.Zip code") %>*</label>
                <%= profile_form.text_field :zip_code, required: true, placeholder: t("doctor.form.Zip code"), label: false, class: 'form-control' %>
              </div>



              <%= render "professional/account/doctor_profile_form", f: f %>


              <div class="form-group text-center add_top_30">
                <%= f.button :submit, "Sign up", class: 'btn_1' %>
              </div>
              <div id="pass-info" class="clearfix"></div>
              <div class="checkbox-holder text-left">
                <div class="checkbox_2">
                  <input type="checkbox" value="accept_2" id="check_2" name="check_2">
                  <label for="check_2"><span>I Agree to the <strong>Terms &amp; Conditions</strong></span></label>
                </div>
              </div>

              </div>
              <p class="text-center">

                <%= render "devise/shared/links" %>
                <small>Has voluptua vivendum accusamus cu. Ut per assueverit temporibus dissentiet. Eum no atqui putant
                  democritum, velit nusquam sententiae vis no.
                </small>
              </p>
            <% end %>
          <% end %>
          </div>
    </div>
    <!-- /row -->
  </div>
  <!-- /register -->
</div>