config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  def draw(routes_name)
    instance_eval(File.read(Rails.root.join("config/routes/#{routes_name}.rb")))
  end

  # tell devise that users management are under accounts path
  devise_for :users, path: 'accounts', :controllers => {:registrations => "public/registrations", :sessions => "sessions"}


  scope :module => 'public' do

    if Rails.env.development?
      get 'welcome/index'
      get "/search" => "professionals#index"
      get "/professionals/search" => "professionals#index"
      get "/professionals/:id" => "doctors#profile", as: :doctor_public_profile
      ## TODO, except for new
      authenticate :user do
        resources :appointments
        get "/profile" => "profile#index"
        get "/settings" => "settings#index"
      end
    else
      get '*' => redirect('/professional/welcome')
    end

    namespace :company do
      # common pages
      get "/" => 'pages#index'
      # contact
      match "/contact" => "contact#index", :as => 'contact_us', via: [:get, :post]
      # features
      match "/features" => "features#index", :as => 'features', via: [:get, :post]
      # product
      get "/product/:page" => "product#pages", :as => 'product_pages'

      # default
      get "/:page" => 'pages#pages', :as => 'pages'
    end

    get "/guide/:page" => "guide#pages", :as => 'guide_pages'

  end


  draw :api

  # professional

  namespace :professional do
    get '/welcome', to: 'welcome#index'
    get '/', to: redirect('professional/dashboard')

    authenticate :user do
      namespace :dashboard do
        get '/', to: 'dashboard#index'
        resources :appointments
        resources :professional_holidays, :path => "/holidays"
        scope as: :scheduler, path: :scheduler do
          post '/update', to: 'professional_availability#update'
          get '/', to: 'professional_availability#index'
        end
        resources :professional_configs, only: [:index, :update]
        get '/pending', to: 'dashboard#pending'
        post '/request-confirmation', to: 'dashboard#request_confirmation'
      end

      namespace :vault do
        resources :documents
        get '/', to: 'vault#index'
      end
    end

    # devise handling for doctor
    devise_scope :user do
      get 'account/new', to: 'account#new', as: 'new_registration'
      post 'account/create', to: 'account#create', as: 'registration'
      match "account/register-as-professional", to: 'account#register_as_professional', as: :register_as_professional, via: [:get, :post]
      authenticate :user do
        get 'profile', to: 'profile#index', as: :profile

        patch 'profile/info', to: 'profile#info', as: :profile_info
        patch 'profile/address', as: :profile_address


        # specialities
        #
        patch 'profile/specialities', as: :profile_specialities

        post 'profile/documents', as: :profile_documents
        post 'profile/update'


        # specialities
        #
        patch 'profile/security', as: :profile_security

        get 'profile/confirm-request-required-documents', to: 'profile#confirm_profile'
        post 'profile/confirm-request-required-documents', to: 'profile#confirm_profile_request'
      end
    end
  end


  authenticate :user do
    namespace 'admin', module: :admin do
      root 'dashboard#index'
      resources :professionals do
        get 'requests'
        member do
          post 'confirm-request'
          post 'decline-request'
          match 'block-account', via: [:get, :post]
          post 'unblock-account'
        end

      end
    end
  end



  if not Rails.env.development?
    root 'professional/welcome#index'
  else
    root 'public/welcome#index'
  end

  # settings
  #
  get "/status/admin-not-found" => "app_status#admin_not_found"


  constraints Constraints::MonitoringWhiteListConstraint.new do
    mount Sidekiq::Web => '/sidekiq'
  end

end

app/controllers/admin/professionals_controller.rb
class Admin::ProfessionalsController < Admin::AdminController

  before_action :set_doctor_profile, :only => [:show, :confirm_request, :decline_request, :block_account], raise: false

  def index
    query = request.query_parameters
    @query = query[:q]
    specialities_ids = []
    if @query.present?
      specialities_ids = Speciality.find_by_field_query(@query).map(&:id)
    end

    @doctors = DoctorProfile
                   .eager_load(:doctor_profile_status, :specialities, :user => [:user_profile])


    ###
    # .joins(:doctor_profile_status)
    #                    .where(doctor_profile_statuses: {status: 'REQUEST'})
    #
    #
    if @query.present?
      @doctors = DoctorProfile
                     .joins(:user => :user_profile) #TODO, fix sanitzation
                     .where("user_profiles.name like '%#{@query}%'")
                     .joins(:specialities)
                     .uniq
      "" ".where(:doctors_specialities => {:speciality_id => specialities_ids})
                     " ""
    end
  end

  def show

  end

  # get all requests for doctor profile
  def requests
    ids = DoctorProfileStatus.where(status: PROFILE_STATUES.request).map(&:id)
    @profiles = DoctorProfile.where(confirmation_status_id: ids).eager_load(:user, :doctor_profile_status, :specialities)
  end


  def block_account
    @professional_block_account_history = ProfessionalBlockAccountHistory.new
    professional_id = params[:id]
    user = User.find(professional_id)
    unless user.nil?
      if user.is_professional?
        @user = user
        # TO, check for existing
        @professional_block_account_history.professional_id = professional_id
        if request.post?
          professional_block = ProfessionalBlockAccountHistory.new(block_account_params)
          professional_block.blocked_by_id = current_user.id
          professional_block.professional_id = professional_id
          if professional_block.save
            user.block_professional_account()
            AdminMailer.block_professional_account(user.id, professional_block.blocking_reason).deliver_now!
            DoctorMailer.account_blocked_notification(user.id, professional_block.blocking_reason).deliver_now!
            flash[:notice] = I18n.t('admin.flash.account_blocked_success')
            redirect_to admin_professionals_path
          else
            @errors = professional_block.errors
          end
        end
      else
        flash[:notice] = I18n.t('This use is not a professional')
        redirect_to admin_professionals_path
      end
    end

  end

  def unblock_account
    redirect_to admin_professionals_path
  end

  # get all requests for doctor profile
  def confirm_request
    message = params[:message]
    @doctor_profile.doctor_profile_status =
        DoctorMailer.send_confirmation_request(@doctor_profile.user_id, message).deliver_later
  end

  def decline_request
    message = params[:message]
    #TODO
    # DoctorMailer.send_decline_request(@doctor_profile.user_id, message).deliver_later
  end

  protected

  def set_doctor_profile
    @doctor_profile = DoctorProfile.find_by_user_id(params[:id])
    # TODO, rais if not exists
  end


  def block_account_params
    params.fetch(:professional_block_account_history, {}).permit([:user_id, :blocking_reason])
  end
end

app/controllers/api/v1/professional/geo_controller.rb
module Api
  module V1
    module Professional
      class GeoController < BaseController
        #caches_action :index, :layout => false
        def reverse
          results = Geocoder.search("#{params[:lat]}, #{params[:lng]}")
          render :json => {:list => results}
        end

        #caches_action :index, :layout => false
        def index
          cities
        end
      end
    end
  end
end

app/controllers/api/v1/professionals_controller.rb
module Api
  module V1
    class ProfessionalsController < BaseController
      include SearchHelper

      def search
        unless params[:location].nil?
          city = City.find_by_id(params[:location])
        end
        @doctors = User
                       .select("users.id, users.email")
                       .eager_load(:user_profile, doctor_profile: {specialities: :speciality})
                       .joins(:professional_holidays)
                       .where("DATE '#{Date.new(2019, 8, 20)}' NOT BETWEEN professional_holidays.start_at AND professional_holidays.end_at")
                       .joins(:user_profile)
                       .joins(:doctor_profile)
                       .where({doctor_profiles: {is_confirmed: true}})
                       .where(doctor_profiles_close_to_query(35.796003, 10.635681, 4000))


        if params[:specialities]
          @doctors = @doctors
                         .joins(:doctors_specialities)
                         .where(:doctors_specialities => {:speciality_id => params[:specialities]})

        end

        @doctors = @doctors.uniq

        "" "
        .select(:id)
                       .eager_load(:doctor_profile)
                       .joins(:doctor_profile)
                       .where({doctor_profiles: {is_confirmed: true}})

                       .joins(:specialities)
                       .where(:doctors_specialities => {:speciality_id => specialities_ids})
                       .uniq
" ""
        render :json => {data: @doctors.as_json(only: [:id],
                                                include: {
                                                    doctor_profile: {
                                                        only: [:full_address, :latitude, :longitude, :address],
                                                        include: {
                                                            specialities: {
                                                                only: [],
                                                                include: {
                                                                    speciality: {
                                                                        only: [:id, :en_fr, :en_ar]
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    },
                                                    user_profile: {only: [:name, :last_name, :title]},
                                                })}
      end


      def recommended
        @doctors = User.all
        render :json => {:data => @doctors}
      end


      def profile
        @doctors = DoctorProfile.all
        render :json => {:data => @doctors}
      end

      def vote

      end

    end
  end
end

app/controllers/professional/account_controller.rb
class Professional::AccountController < Devise::RegistrationsController
  include ProfessionalHelper

  #https://stackoverflow.com/questions/41266207/before-process-action-callback-authenticate-user-has-not-been-defined#41266746
  skip_before_action :is_doctor?, :only => [:create, :register_as_professional], raise: false
  skip_before_action :idle_profile_status?, :only => [:create, :register_as_professional], raise: false

  before_action :configure_permitted_parameters, if: :devise_controller?

  def new
    super do
      resource.build_user_profile
      resource.build_doctor_profile
    end
  end

  def create
    super do
      if resource.persisted?
        send_request_doctor_mail(resource)
      end
    end
  end

  # A user already create an account but
  def register_as_professional
    if current_user
      if request.method === "POST"
        @profile = current_user.create_doctor_profile!()
        puts (@profile)
        ## @profile TODO add
        if @profile.save!
          flash[:success] = t("Request for becoming doctor is confirmed")
          # Tell the UserMailer to send a welcome email after save
          send_request_doctor_mail(current_user)
          redirect_to :doctor_profile
        else
          flash[:error] = t('Something went wrong !')
        end
      else
        # if get, build profile
        @profile = current_user.build_doctor_profile
      end
    else
      redirect_to :doctor_new_registration
    end

  end

  protected

  def after_sign_up_path_for(resource)
    :doctor_profile_update
  end

  def send_request_doctor_mail (user)
    AdminMailer.request_for_doctor_account(user.id).deliver_later
    UserMailer.request_doctor_profile(user.id).deliver_later
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :password, :password_confirmation,
                                                       {user_profile_attributes: [:name, :last_name, :birthday, :address, :zip_code]},
                                                       {doctor_profile_attributes: [:street, :latitude, :longitude, :full_address, :zip_code]}])
  end

end

app/controllers/professional/dashboard/appointments_controller.rb
class Professional::Dashboard::AppointmentsController < Professional::ProfessionalController
  def index

    @consultations = current_user.consultations
    @month = Date.current.beginning_of_month
    unless params[:month].nil?
      begin
        @month = Date.strptime(params[:month], "%Y-%m-%d")
      rescue
        nil
      end
    end

  end

  # confirm appointment
  # Check for disponiblity
  # disable disponibilites
  def confirm

  end
end

app/controllers/professional/dashboard/dashboard_controller.rb
class Professional::Dashboard::DashboardController < Professional::ProfessionalController
  skip_before_action :waiting_confirmation_status?, :only => [:pending, :request_confirmation]

  def index
    render 'professional/dashboard/index'
  end

  def pending
    render 'professional/dashboard/pending', :layout => false
  end

  def request_confirmation
    user_id = current_user.id
    AdminMailer.request_for_doctor_account_confirmation(user_id).deliver_now
    UserMailer.request_doctor_profile_confirmation(user_id).deliver_later
  end
end

app/controllers/professional/dashboard/professional_configs_controller.rb
class Professional::Dashboard::ProfessionalConfigsController < Professional::ProfessionalController

  before_action :set_professional_config, only: [:index, :update]


  def index
    render 'update'
  end

  # POST /professional_configs
  def update

    @professional_config.update(update_params.except(:user))

    user_params = update_params[:user]

    current_user.update!(user_params)

    if current_user.phone_number_changed?
      current_user.two_factor_via_confirmed = false
    end

    redirect_to professional_dashboard_professional_configs_path
  end


  private



  # Never trust parameters from the scary internet, only allow the white list through.
  def update_params

  end

end

app/controllers/professional/professional_controller.rb
class Professional::ProfessionalController < ApplicationController
  include ProfessionalHelper
  before_action :is_doctor?
  before_action :idle_profile_status?
  before_action :waiting_confirmation_status?
  layout 'doctor'
end

app/controllers/professional/vault/documents_controller.rb
class  Professional::Vault::DocumentsController < Professional::ProfessionalController

  def index

  end

end

app/controllers/professional/vault/vault_controller.rb
class Professional::Vault::VaultController < Professional::ProfessionalController
  def index
    render 'professional/vault/index'
  end

  private

  def profile_request_params
    params.require(:doctor_profile).permit(files: [], speciality_ids: [])
  end


  def update_params
    params.require(:doctor_profile).permit(:city, :avatar, speciality_ids: [])
  end
end

app/helpers/professional/account_helper.rb
module Professional::AccountHelper
  PROFILE_STATUES = {
      :request => 'REQUEST'
  }
end

app/helpers/professional/appointments_helper.rb
module Professional::AppointmentsHelper

  def appointments_future_count
    Appointment.where({:doctor_id => current_user.id}).where('time > ?', Time.now).count()
  end

end

app/helpers/professional/dashboard_helper.rb
module Professional::DashboardHelper
end

app/helpers/professional/doctor_availability_helper.rb
module Professional::DoctorAvailabilityHelper

  def should_configure_scheduler?
    current_user.doctor_availabilities.count == 0
  end

  def should_configure_system?
    current_user.professional_config.nil?
  end

end

app/helpers/professional_helper.rb
module ProfessionalHelper
  def is_doctor?
    unless current_user&.is_doctor?
      redirect_to doctor_register_as_professional_path
    end
  end

  def idle_profile_status?
    unless current_user&.doctor_profile&.is_confirmed?
      if current_user.doctor_profile.idle_profile_status?
        redirect_to doctor_profile_confirm_request_required_documents_path
      end
    end
  end
  # check if doctor is waiting request
  def waiting_confirmation_status?
    unless current_user&.doctor_profile&.is_confirmed?
      if current_user.doctor_profile.waiting_confirmation_status?
        redirect_to doctor_dashboard_pending_path
      end
    end
  end

  def can_proceed_view_if_not_confirmed
    controller = controller_name
    (controller == 'profile_controller' && action_name == "confirm_profile") || current_user.doctor_profile.is_confirmed
  end

  def set_request_variant
    request.format = 'html' if request.format == 'mobile'
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/professional/welcome/_navbar_out_doctor.html.erb
<nav class="navbar main-navbar is-transparent no-shadow"
     <% if clone %>
     id="navbar-clone"
     <% end %>
     role="navigation" aria-label="main navigation">
  <div class="container">
    <div class="navbar-brand">
      <a href="/professional/welcome" class="navbar-item">
        <%= render 'partials/logo', :locals => {:pro => true} %>&nbsp;<span class="tag pro-logo">Pro</span>
      </a>
    </div>

    <div id="navbar-menu" class="navbar-menu is-static">
      <div class="navbar-end">
        <a href="#doctor_features" class="navbar-item is-secondary">
          <%= t('doctor.welcome.header.produit') %>
        </a>
        <a href="#pricing" class="navbar-item is-secondary">
          <%= t('doctor.welcome.header.pricing') %>
        </a>
        <%= link_to(company_pages_path('security-and-data'), :class => "navbar-item is-secondary") do %>

          <%= t('doctor.welcome.header.security') %>
        <% end %>
        <% if Rails.env.development? %>
          <%= link_to new_user_session_path, class: 'navbar-item' do %>
          <span class="button bg-primary-5 rounded ">
              <%= t('account.sign_in') %>
          </span>
          <% end %>

          <%= link_to professional_new_registration_path, class: 'navbar-item' do %>
        <span class="button  rounded">
                         <%= t('account.doctor.sign_up') %>
                    </span>
          <% end %>
        <% else %>
          <%= link_to company_pages_path('contact'), class: 'navbar-item' do %>
         <span class="bg-primary-5 button rounded">
               <%= t('footer.guide_links.contact') %>
                    </span>

          <% end %>
        <% end %>

      </div>
    </div>
  </div>
</nav>

app/views/professional/welcome/index.html.erb
<% content_for :header do %>
  <%= render 'professional/welcome/navbar_out_doctor', clone: false %>
  <%= render 'professional/welcome/navbar_out_doctor', clone: true %>
<% end %>
<section class="hero is-fullheight-with-navbar is-default is-bold">
  <div class="hero-body">
    <div class="container">
      <div class="columns is-vcentered">
        <div class="column is-5 is-offset-1 landing-caption">
          <h1 class="title is-1 is-bold is-spaced">
            <%= t('doctor.welcome.hero.title') %>
          </h1>
          <h2 class="subtitle is-5 is-muted">
            <%= t('doctor.welcome.hero.subtitle') %>
          </h2>

          <p>
            <% if Rails.env.development? %>
              <%= link_to new_user_session_path, class: 'button  has-shadow  rounded bg-primary-5' do %>
                <%= t('account.doctor.sign_up') %>
              <% end %>
              <a href="#contact_us" class="button bg-support-red-6 has-shadow rounded">
                watch demo
              </a>
            <% else %>
              <a href="#contact_us" class="button rounded bg-primary-5 has-shadow  rounded">
                <%= t('doctor.welcome.hero.contact_us') %>
              </a>
            <% end %>


          </p>
        </div>
        <div class="column is-5 is-offset-1">
          <figure class="image is-4by3">
            <img src="<%= asset_path('landing/doctor-landing.svg') %>" alt="Doctor">
          </figure>
        </div>

      </div>
    </div>
  </div>
</section>
<section class="section is-medium" id="doctor_features">
  <div class="container">
    <div class="title-wrapper has-text-centered">
      <h2 class="title is-2"> <%= t("doctor.welcome.features.title") %></h2>
      <h3 class="subtitle is-5 is-muted"><%= t("doctor.welcome.features.subtitle") %> </h3>
      <div class="divider is-centered"></div>
    </div>

    <div class="content-wrapper">
      <div class="columns is-multiline icon-list has-text-centered has-text-justified">
        <div class="column is-3 feature">
          <div class="has-text-centered">

            <%= render :partial => 'partials/icon', :locals => {:icon => 'icon-location-pin'} %>

            <h4>Visiblité</h4>
            <p>Plus proche </p>
          </div>
        </div>
        <div class="column is-3 feature">
          <div class="has-text-centered">

            <%= render :partial => 'partials/icon', :locals => {:icon => 'icon-security-check'} %>

            <h4>Sécurité</h4>
            <p> Zero knowledge </p>
          </div>
        </div>
        <div class="column is-3 feature">
          <div class="has-text-centered">
            <%= render :partial => 'partials/icon', :locals => {:icon => 'icon-document-notes'} %>

            <h4>Partage des données</h4>
            <p>Chiffrement de bout en bout</p>
          </div>
        </div>
        <div class="column is-3 feature">
          <div class="has-text-centered">
            <%= render :partial => 'partials/icon', :locals => {:icon => 'icon-phone-ring'} %>
            <h4>SMS</h4>
            <p>Notifications </p>
          </div>
        </div>

        <div class="column is-3 feature">
          <div class="has-text-centered">
            <%= render :partial => 'partials/icon', :locals => {:icon => 'icon-brick'} %>
            <h4>Intégrations</h4>
            <p> Personnalisation et intégration avec d'autres systèmes</p>
          </div>
        </div>

        <div class="column is-3 feature">
          <div class="has-text-centered">
            <%= render :partial => 'partials/icon', :locals => {:icon => 'icon-survey'} %>
            <h4>Suivi</h4>
            <p>Suivi des patients </p>
          </div>
        </div>
        <div class="column is-3 feature">
          <div class="has-text-centered">
            <%= render :partial => 'partials/icon', :locals => {:icon => 'icon-umbrella'} %>
            <h4>Accessibilité</h4>
            <p>Compatible et accessible avec la majorité des navigateurs</p>
          </div>
        </div>

        <div class="column is-3 feature">
          <div class="has-text-centered">
            <%= render :partial => 'partials/icon', :locals => {:icon => 'icon-notification'} %>

            <h4>Notifications</h4>
            <p>Restez toujours informé</p>
          </div>
        </div>
        <div class="column is-3 feature">
          <div class="has-text-centered">
            <%= render :partial => 'partials/icon', :locals => {:icon => 'icon-calendar'} %>
            <h4>Vacances</h4>
            <p>Some feature text</p>
          </div>
        </div>
        <div class="column is-3 feature">
          <div class="has-text-centered">
            <%= render :partial => 'partials/icon', :locals => {:icon => 'icon-clouds'} %>
            <h4>Cloud </h4>
            <p>7j/7 24h/4 </p>
          </div>
        </div>

      </div>
    </div>
  </div>
</section>
<section class="section is-medium is-relative welcome-full-background__container">

  <img class="welcome-full-background delay-10" data-animation="fadeInUp" src="https://images.unsplash.com/photo-1553356009-50faee7aa84c?ixlib=rb-1.2.1&auto=format&fit=crop&w=max&q=100">

  <div class="container">

    <div class="title-wrapper has-text-centered">
      <h2 class="title is-2"><%= t('features.product.title') %></h2>
      <h3 class="subtitle is-5 is-muted"><%= t('features.product.subtitle') %></h3>
    </div>
    <br/>
    <div class="columns">
      <div class="column is-10 is-offset-1">
        <div class="has-text-centered">
          <img class="pushed-image" src="<%= asset_path('illustrations/mockups/app-mockup.png') %>">
        </div>
      </div>
    </div>
  </div>
</section>


<section class="section is-medium" id="pricing">
  <div class="container">
    <div class="title-wrapper has-text-centered">
      <h2 class="title is-2">Offres</h2>
      <h3 class="subtitle is-4 is-muted"><%= t('doctor.welcome.plans.choose_plan') %></h3>
      <h3 class="subtitle is-6 is-muted"><%= t('doctor.welcome.plans.start_free') %></h3>
      <div class="divider is-centered"></div>
    </div>

    <div class="pricing-wrap columns is-multiline">
      <div class="feature-card is-pricing has-text-centered is-4-tablet">
        <h3 class="plan-name">Pro Cloud</h3>
        <div class="feature-card-middle is-flex ">
          <img src="<%= asset_path('illustrations/pricing/1.svg') %>" alt="">
          <div>
            <span class="price">50</span>
            <small class="has-text-weight-light is-small is-5">DT / mois</small>
          </div>

          <ul class="has-text-left p-l-10 m-t-10">
            <li> ✔ Gestion Rendez vous et patients</li>
            <li> ✔ Page profil public</li>
            <li> ✔ SMS et notifications</li>
            <li> ✔ Partage dossier medical chiffré</li>
            <li> ✔ Stockage chiffré</li>
            <li> ✔ Chiffrement bout en bout</li>
            <li> ✔ Télémédecine</li>
          </ul>
        </div>


      </div>
      <div class="feature-card is-pricing has-text-centered is-4-tablet">
        <h3 class="plan-name Pro ">On promise

        </h3>
        <small> [Produit + installation] (*)</small>
        <div class="feature-card-middle is-flex ">
          <img src="<%= asset_path('illustrations/pricing/2.svg') %>" alt="">
          <span class="has-text-danger">
            3000 <small class="has-text-weight-light is-small is-5">DT / an</small>
          </span>
          <ul class="has-text-left p-l-10 m-t-10">
            <li class="has-text-success"> ✔ Services Pro Cloud</li>
            <li> ✔ Hébérgé chez vous ...</li>
            <li> ✔ Habillage personalisé (Logos / Libellés)</li>
            <li> ✔ Mise à jour avec la version cloud</li>
          </ul>
          <br/>
          <div class="has-text-left m-t-5">
            <span class="tag is-warning">Option</span> Application mobile personnalisée à partir de
            <small class="has-text-weight-light is-small is-5">5000 dt</small>
          </div>
        </div>

        <%= link_to(company_pages_path('contact'), :class => "button is-fullwidth is-bold") do %>
          <%= t('footer.guide_links.contact') %>
        <% end %>
      </div>
      <div class="feature-card is-pricing has-text-centered is-4-tablet">
        <h3 class="plan-name has-text-weight-bold">Clinique / Centre médical et dentaire
        </h3>
        <div class="feature-card-middle is-flex ">
          <img src="<%= asset_path('illustrations/pricing/3.svg') %>" alt="">
        </div>
        <%= link_to(company_pages_path('contact'), :class => "button is-fullwidth is-bold") do %>
          <%= t('footer.guide_links.contact') %>
        <% end %>
      </div>
    </div>

    <p class="m-t-20 m-l-20 m-r-10">
      * Prix du produit, modification logo et installation seulement hors prix d'autres composants : nom de domaine,
      certificat SSL, serveurs, stockage, email, serveur sms
      <br/>
      Systèmes d'exploitation : Ubuntu LTS 16.10 / Ubuntu LTS 18.04 / Ubuntu Server 18.04 LTS et Docker
      .
      <br/>
      Si vous voulez le package complet <%= link_to(company_pages_path('contact'), :class => "is-bold") do %>
        <%= t('footer.guide_links.contact') %>
      <% end %>
    </p>
  </div>

</section>



<section class="section is-medium" id="pack_brand">
  <div class="container">
    <div class="columns">
      <div class="column is-centered-tablet-portrait">
        <h1 class="title section-title">Votre pack <b>On promise </b></h1>
        <h3 class="subtitle is-4 is-muted">Votre cabinet digitale en moins de 7 jours</h3>
        <div class="divider"></div>
      </div>
      <div class="column is-8 ">

        <!-- icon block -->
        <article class="media icon-box">
          <figure class="media-left">
            <p class="image">
              <img src="<%= asset_path('illustrations/icons/laptop-globe.svg') %>">
            </p>
          </figure>
          <div class="media-content">
            <div class="content">
              <p>
                <span class="has-text-weight-bold">Plus simple que jamais</span><br/>
                <span class="icon-box-text">En cloud, l'application est disponible 24h 7j/7j ....
              </span>
            </div>
          </div>
        </article>
        <!-- /icon block -->

        <!-- icon block -->
        <article class="media icon-box">
          <figure class="media-left">
            <p class="image">
              <img src="<%= asset_path('illustrations/icons/mobile-feed.svg') %>">
            </p>
          </figure>
          <div class="media-content">
            <div class="content">
              <p>
                <span class="has-text-weight-bold">Votre application mobile personalisée </span>
                <span class="icon-box-text">Une application mobile pour personaliser vos services. Contactez nous pour une démo </span>
              </p>
            </div>
          </div>
        </article>
        <!-- /icon block -->

        <!-- icon block -->
        <article class="media icon-box">
          <figure class="media-left">
            <p class="image">

              <img src="<%= asset_path('illustrations/icons/doc-sync.svg') %>">
            </p>
          </figure>
          <div class="media-content">
            <div class="content">
              <p>
                <span class="has-text-weight-bold">Chiffrement des données privées</span><br/>
                <span class="icon-box-text">Les fichiers et les informations liées à vos patients sont tous encryptés, seuls vous et vos patient peuvent accéder à ces données .</span>
              </p>
            </div>
          </div>
        </article>
        <!-- /icon block -->
      </div>
    </div>
  </div>
</section>



<%= render 'partials/contact' %>


<div id="auth-modal" class="modal">
  <div class="modal-background"></div>
  <div class="modal-content">
  </div>
  <button class="modal-close is-large" aria-label="close"></button>
</div>