config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  def draw(routes_name)
    instance_eval(File.read(Rails.root.join("config/routes/#{routes_name}.rb")))
  end

  # tell devise that users management are under accounts path
  devise_for :users, path: 'accounts', :controllers => {:registrations => "public/registrations", :sessions => "sessions"}


  scope :module => 'public' do

    if Rails.env.development?
      get 'welcome/index'
      get "/search" => "professionals#index"
      get "/professionals/search" => "professionals#index"
      get "/professionals/:id" => "doctors#profile", as: :doctor_public_profile
      ## TODO, except for new
      authenticate :user do
        resources :appointments
        get "/profile" => "profile#index"
        get "/settings" => "settings#index"
      end
    else
      get '*' => redirect('/professional/welcome')
    end

    namespace :company do
      # common pages
      get "/" => 'pages#index'
      # contact
      match "/contact" => "contact#index", :as => 'contact_us', via: [:get, :post]
      # features
      match "/features" => "features#index", :as => 'features', via: [:get, :post]
      # product
      get "/product/:page" => "product#pages", :as => 'product_pages'

      # default
      get "/:page" => 'pages#pages', :as => 'pages'
    end

    get "/guide/:page" => "guide#pages", :as => 'guide_pages'

  end


  draw :api

  # professional

  namespace :professional do
    get '/welcome', to: 'welcome#index'
    get '/', to: redirect('professional/dashboard')

    authenticate :user do
      namespace :dashboard do
        get '/', to: 'dashboard#index'
        resources :appointments
        resources :professional_holidays, :path => "/holidays"
        scope as: :scheduler, path: :scheduler do
          post '/update', to: 'professional_availability#update'
          get '/', to: 'professional_availability#index'
        end
        resources :professional_configs, only: [:index, :update]
        get '/pending', to: 'dashboard#pending'
        post '/request-confirmation', to: 'dashboard#request_confirmation'
      end

      namespace :vault do
        resources :documents
        get '/', to: 'vault#index'
      end
    end

    # devise handling for doctor
    devise_scope :user do
      get 'account/new', to: 'account#new', as: 'new_registration'
      post 'account/create', to: 'account#create', as: 'registration'
      match "account/register-as-professional", to: 'account#register_as_professional', as: :register_as_professional, via: [:get, :post]
      authenticate :user do
        get 'profile', to: 'profile#index', as: :profile

        patch 'profile/info', to: 'profile#info', as: :profile_info
        patch 'profile/address', as: :profile_address


        # specialities
        #
        patch 'profile/specialities', as: :profile_specialities

        post 'profile/documents', as: :profile_documents
        post 'profile/update'


        # specialities
        #
        patch 'profile/security', as: :profile_security

        get 'profile/confirm-request-required-documents', to: 'profile#confirm_profile'
        post 'profile/confirm-request-required-documents', to: 'profile#confirm_profile_request'
      end
    end
  end


  authenticate :user do
    namespace 'admin', module: :admin do
      root 'dashboard#index'
      resources :professionals do
        get 'requests'
        member do
          post 'confirm-request'
          post 'decline-request'
          match 'block-account', via: [:get, :post]
          post 'unblock-account'
        end

      end
    end
  end



  if not Rails.env.development?
    root 'professional/welcome#index'
  else
    root 'public/welcome#index'
  end

  # settings
  #
  get "/status/admin-not-found" => "app_status#admin_not_found"


  constraints Constraints::MonitoringWhiteListConstraint.new do
    mount Sidekiq::Web => '/sidekiq'
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  before_create :set_default_role
  after_create :init_profile
  after_initialize :set_default_role, :if => :new_record?

  #devise :two_factor_authenticatable,
  #      :otp_secret_encryption_key => ENV['BLOOSA_OTP_ENCRYPTION_KEY']
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  # note, we removed the :database_authenticatable to activate encryption_key_env
  devise :database_authenticatable, :registerable, #, :database_authenticatable,
         :confirmable, :recoverable, :rememberable, :trackable, :validatable


  belongs_to :role

  has_one :profile, class_name: 'UserProfile', dependent: :destroy
  has_one :user_profile, dependent: :destroy
  accepts_nested_attributes_for :user_profile


  ### appointments
  has_many :appointments, dependent: :destroy, foreign_key: :patient_id


  ################# Doctor configuration
  has_one :doctor_profile, dependent: :destroy
  accepts_nested_attributes_for :doctor_profile
  ### specialitites
  has_many :doctors_specialities, foreign_key: :doctor_id, dependent: :destroy
  ### specialitites
  has_many :specialities, through: :doctors_specialities
  ### specialitites
  has_many :professional_holidays, foreign_key: :professional_id, dependent: :destroy
  ### avalabilities
  has_many :doctor_availabilities, foreign_key: :doctor_id, dependent: :destroy
  ###
  has_many :doctor_speciality_estimation_times, foreign_key: :professional_id, dependent: :destroy

  ### doctor
  has_many :consultations, foreign_key: :doctor_id, class_name: 'Appointment'


  ## Conversation
  has_many :authored_conversations, class_name: 'Conversation', foreign_key: 'author_id'
  has_many :received_conversations, class_name: 'Conversation', foreign_key: 'received_id'

  ## Messages
  has_many :conversation_messages, dependent: :destroy

  ## Doctor votes

  ## Messages
  has_many :doctor_votes, dependent: :destroy


  ## professional_config
  has_one :professional_config, foreign_key: :professional_id, dependent: :destroy


  attr_encrypted :phone_number, key: ENV['BLOOSA_PHONE_NUMBER_ENCRYPTION_KEY']
  validates_presence_of :phone_number, :if => :otp_required_for_login?

  def is_doctor?
    DoctorProfile.where(user: self).any?
  end

  def is_professional?
    DoctorProfile.where(user: self).any?
  end

  def is_professional_blocked?
    doctor_profile = DoctorProfile.where(user: self).first
    !doctor_profile.is_confirmed && doctor_profile.doctor_profile_status === DoctorProfileStatus.find_by_status('BLOCKED')
  end

  def block_professional_account
    doctor_profile = DoctorProfile.where(user: self).first
    doctor_profile.is_confirmed = false
    doctor_profile.doctor_profile_status = DoctorProfileStatus.find_by_status('BLOCKED')
    doctor_profile.save!
  end

  def is_admin?
    self.role&.id == Role.find_by_name('admin').id
  end

  def role?(role_name)
    role == role_name
  end

  #TODO , look for banned or something similar
  def can_login?(ability = '')
    true
  end

  # TODO
  def active_for_authentication?
    true
  end

  protected


  private


  def set_default_role
    self.role ||= Role.find_by_name('patient')
  end

  def init_profile
    # Tell the UserMailer to send a welcome email after save
    UserMailer.welcome_email(self.id).deliver_later!
  end

  def valid_two_factor_confirmation
    return true unless two_factor_just_set || phone_changed_with_two_factor
    self.unconfirmed_two_factor = true
  end

  def send_two_factor_authentication_code(code)
    # Send code via SMS, etc.
    puts code
  end

  def need_two_factor_authentication?(request)
    request.ip != '127.0.0.1'
  end


end

app/controllers/admin/professionals_controller.rb
class Admin::ProfessionalsController < Admin::AdminController

  before_action :set_doctor_profile, :only => [:show, :confirm_request, :decline_request, :block_account], raise: false

  def index
    query = request.query_parameters
    @query = query[:q]
    specialities_ids = []
    if @query.present?
      specialities_ids = Speciality.find_by_field_query(@query).map(&:id)
    end

    @doctors = DoctorProfile
                   .eager_load(:doctor_profile_status, :specialities, :user => [:user_profile])


    ###
    # .joins(:doctor_profile_status)
    #                    .where(doctor_profile_statuses: {status: 'REQUEST'})
    #
    #
    if @query.present?
      @doctors = DoctorProfile
                     .joins(:user => :user_profile) #TODO, fix sanitzation
                     .where("user_profiles.name like '%#{@query}%'")
                     .joins(:specialities)
                     .uniq
      "" ".where(:doctors_specialities => {:speciality_id => specialities_ids})
                     " ""
    end
  end

  def show

  end

  # get all requests for doctor profile
  def requests
    ids = DoctorProfileStatus.where(status: PROFILE_STATUES.request).map(&:id)
    @profiles = DoctorProfile.where(confirmation_status_id: ids).eager_load(:user, :doctor_profile_status, :specialities)
  end


  def block_account
    @professional_block_account_history = ProfessionalBlockAccountHistory.new
    professional_id = params[:id]
    user = User.find(professional_id)
    unless user.nil?
      if user.is_professional?
        @user = user
        # TO, check for existing
        @professional_block_account_history.professional_id = professional_id
        if request.post?
          professional_block = ProfessionalBlockAccountHistory.new(block_account_params)
          professional_block.blocked_by_id = current_user.id
          professional_block.professional_id = professional_id
          if professional_block.save
            user.block_professional_account()
            AdminMailer.block_professional_account(user.id, professional_block.blocking_reason).deliver_now!
            DoctorMailer.account_blocked_notification(user.id, professional_block.blocking_reason).deliver_now!
            flash[:notice] = I18n.t('admin.flash.account_blocked_success')
            redirect_to admin_professionals_path
          else
            @errors = professional_block.errors
          end
        end
      else
        flash[:notice] = I18n.t('This use is not a professional')
        redirect_to admin_professionals_path
      end
    end

  end

  def unblock_account
    redirect_to admin_professionals_path
  end

  # get all requests for doctor profile
  def confirm_request
    message = params[:message]
    @doctor_profile.doctor_profile_status =
        DoctorMailer.send_confirmation_request(@doctor_profile.user_id, message).deliver_later
  end

  def decline_request
    message = params[:message]
    #TODO
    # DoctorMailer.send_decline_request(@doctor_profile.user_id, message).deliver_later
  end

  protected

  def set_doctor_profile
    @doctor_profile = DoctorProfile.find_by_user_id(params[:id])
    # TODO, rais if not exists
  end


  def block_account_params
    params.fetch(:professional_block_account_history, {}).permit([:user_id, :blocking_reason])
  end
end

app/controllers/api/v1/mobile/profile_controller.rb
module Api
  module V1
    module Mobile
      class ProfileController < BaseController
        def index
          render :json => {:data => 'hello'}
        end
      end
    end
  end
end

app/controllers/api/v1/professional/geo_controller.rb
module Api
  module V1
    module Professional
      class GeoController < BaseController
        #caches_action :index, :layout => false
        def reverse
          results = Geocoder.search("#{params[:lat]}, #{params[:lng]}")
          render :json => {:list => results}
        end

        #caches_action :index, :layout => false
        def index
          cities
        end
      end
    end
  end
end

app/controllers/api/v1/professionals_controller.rb
module Api
  module V1
    class ProfessionalsController < BaseController
      include SearchHelper

      def search
        unless params[:location].nil?
          city = City.find_by_id(params[:location])
        end
        @doctors = User
                       .select("users.id, users.email")
                       .eager_load(:user_profile, doctor_profile: {specialities: :speciality})
                       .joins(:professional_holidays)
                       .where("DATE '#{Date.new(2019, 8, 20)}' NOT BETWEEN professional_holidays.start_at AND professional_holidays.end_at")
                       .joins(:user_profile)
                       .joins(:doctor_profile)
                       .where({doctor_profiles: {is_confirmed: true}})
                       .where(doctor_profiles_close_to_query(35.796003, 10.635681, 4000))


        if params[:specialities]
          @doctors = @doctors
                         .joins(:doctors_specialities)
                         .where(:doctors_specialities => {:speciality_id => params[:specialities]})

        end

        @doctors = @doctors.uniq

        "" "
        .select(:id)
                       .eager_load(:doctor_profile)
                       .joins(:doctor_profile)
                       .where({doctor_profiles: {is_confirmed: true}})

                       .joins(:specialities)
                       .where(:doctors_specialities => {:speciality_id => specialities_ids})
                       .uniq
" ""
        render :json => {data: @doctors.as_json(only: [:id],
                                                include: {
                                                    doctor_profile: {
                                                        only: [:full_address, :latitude, :longitude, :address],
                                                        include: {
                                                            specialities: {
                                                                only: [],
                                                                include: {
                                                                    speciality: {
                                                                        only: [:id, :en_fr, :en_ar]
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    },
                                                    user_profile: {only: [:name, :last_name, :title]},
                                                })}
      end


      def recommended
        @doctors = User.all
        render :json => {:data => @doctors}
      end


      def profile
        @doctors = DoctorProfile.all
        render :json => {:data => @doctors}
      end

      def vote

      end

    end
  end
end

app/controllers/professional/dashboard/appointments_controller.rb
class Professional::Dashboard::AppointmentsController < Professional::ProfessionalController
  def index

    @consultations = current_user.consultations
    @month = Date.current.beginning_of_month
    unless params[:month].nil?
      begin
        @month = Date.strptime(params[:month], "%Y-%m-%d")
      rescue
        nil
      end
    end

  end

  # confirm appointment
  # Check for disponiblity
  # disable disponibilites
  def confirm

  end
end

app/controllers/professional/dashboard/dashboard_controller.rb
class Professional::Dashboard::DashboardController < Professional::ProfessionalController
  skip_before_action :waiting_confirmation_status?, :only => [:pending, :request_confirmation]

  def index
    render 'professional/dashboard/index'
  end

  def pending
    render 'professional/dashboard/pending', :layout => false
  end

  def request_confirmation
    user_id = current_user.id
    AdminMailer.request_for_doctor_account_confirmation(user_id).deliver_now
    UserMailer.request_doctor_profile_confirmation(user_id).deliver_later
  end
end

app/controllers/professional/professional_controller.rb
class Professional::ProfessionalController < ApplicationController
  include ProfessionalHelper
  before_action :is_doctor?
  before_action :idle_profile_status?
  before_action :waiting_confirmation_status?
  layout 'doctor'
end

app/helpers/professional/account_helper.rb
module Professional::AccountHelper
  PROFILE_STATUES = {
      :request => 'REQUEST'
  }
end

app/helpers/professional/appointments_helper.rb
module Professional::AppointmentsHelper

  def appointments_future_count
    Appointment.where({:doctor_id => current_user.id}).where('time > ?', Time.now).count()
  end

end

app/helpers/professional/dashboard_helper.rb
module Professional::DashboardHelper
end

app/helpers/professional/doctor_availability_helper.rb
module Professional::DoctorAvailabilityHelper

  def should_configure_scheduler?
    current_user.doctor_availabilities.count == 0
  end

  def should_configure_system?
    current_user.professional_config.nil?
  end

end

app/helpers/professional_helper.rb
module ProfessionalHelper
  def is_doctor?
    unless current_user&.is_doctor?
      redirect_to doctor_register_as_professional_path
    end
  end

  def idle_profile_status?
    unless current_user&.doctor_profile&.is_confirmed?
      if current_user.doctor_profile.idle_profile_status?
        redirect_to doctor_profile_confirm_request_required_documents_path
      end
    end
  end
  # check if doctor is waiting request
  def waiting_confirmation_status?
    unless current_user&.doctor_profile&.is_confirmed?
      if current_user.doctor_profile.waiting_confirmation_status?
        redirect_to doctor_dashboard_pending_path
      end
    end
  end

  def can_proceed_view_if_not_confirmed
    controller = controller_name
    (controller == 'profile_controller' && action_name == "confirm_profile") || current_user.doctor_profile.is_confirmed
  end

  def set_request_variant
    request.format = 'html' if request.format == 'mobile'
  end
end

app/views/professional/profile/_account.html.erb
deactivate my account
  notifications

app/views/professional/profile/_address.html.erb
<%= simple_form_for(@doctor_profile, url: {action: @tab}) do |f| %>

  <div class="container-fluid">
  <!-- /row-->
  <!-- /box_general-->
  <div class="field">
    <label class="label">Addresse</label>
    <p class="control">
      <%= text_field :doctor_profile, :full_address, {class: "input"} %>
    </p>
  </div>
  <div class="field is-horizontal">
    <div class="field-body">
      <div class="field">
        <label class="label">Ville</label>
        <div class="control">
          <div class="select">
            <%= f.collection_select(:city_id, City.order(:name_fr), :id, :name, {include_blank: t('city')}) %>
          </div>
        </div>
      </div>
    </div>
    <div class="field-body">
      <div class="field">
        <label class="label">Code postal</label>
        <div class="control">
          <%= text_field :doctor_profile, :zip_code, {class: "input"} %>
        </div>
      </div>
    </div>
  </div>
</div>

<%= f.submit t('submit'), :type => 'submit', :class => 'button medium' %>
<% end %>

app/views/professional/profile/_documents.html.erb
<span class="app-notification is-warning">
        <% cache "icons_icon-notification" do %>
              <%= render :partial => 'partials/icon', :locals => {:icon => 'icon-notification'} %>
            <% end %>
  Ces documents sont nécessaires  afin que vous puissiez proposer votre service. Il ne faut pas mettre des documents privée,
    pour toute document privées, merci d'utliser le service <%= link_to(professional_vault_path) do %><%= t('vault') %><% end %>
    </span>
<% @doctor_profile.files.each do |file| %>

  <div>

    <%= link_to rails_blob_path(file, disposition: "attachment") do %>
      <%= file.filename %>
    <% end %>
  </div>
<% end %>
<%= simple_form_for(@doctor_profile, url: {action: @tab}) do |f| %>


<% end %>

app/views/professional/profile/_info.html.erb
<%= simple_form_for(@doctor_profile, url: {action: @tab}) do |f| %>

  <div class="field is-horizontal">
    <div class="field-body">
      <div class="field">
        <label class="label">Name</label>
        <p class="control">
          <%= text_field :user_profile, :name, {class: "input", value: @doctor_profile.user.profile.name} %>
        </p>
      </div>
      <div class="field">
        <label class="label">Last name</label>
        <p class="control">
          <%= text_field :user_profile, :last_name, {class: "input", value: @doctor_profile.user.profile.last_name} %>
        </p>
      </div>
    </div>
  </div>

  <div class="field is-horizontal">
    <div class="field-body">
      <div class="field">
        <label class="label">Titre</label>
        <div class="control">
          <%= text_field :user_profile, :title, {class: "input", placeholder: "Docteur / Prof ...", value: @doctor_profile.user.profile.title} %>
        </div>
      </div>

      <div class="field">
        <label class="label">#TODO</label>
        <div class="control">
          <div class="select">
            <%= select_tag "user_profile[gender]", options_for_select(%w(M/Mme? M. Mme.)), {class: "select input"} %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <%= f.submit t('submit'), :type => 'submit', :class => 'button medium' %>
<% end %>

app/views/professional/profile/_security.html.erb
<%= simple_form_for(@doctor_profile, url: {action: @tab}) do |f| %>
<%= f.fields_for :user do |user_tfa_f| %>

    <h5 class="subtitle  is-6">Two factor authentification <%= link_to(company_pages_path('security-and-data')) do %> En
        savoir plus ?
      <% end %> </h5>
    <div class="field">
    <label class="label"><%= t('simple_form.labels.professional_block_account_history.tfa_activated') %></label>
    <%= user_tfa_f.input :otp_required_for_login, input_html: {class: 'checkbox reset-checkbox-form', type: 'checkbox', checked: current_user.otp_required_for_login}, label: false %>
  </div>

  <div class="field">
    <label class="label"><%= t('simple_form.labels.professional_block_account_history.tfa_via') %>
      <small> (* Pour le moment, bloosa supporte la double authentificatio via sms ou email</small>
      )</label>

    <%= user_tfa_f.input :two_factor_via, :collection => ['SMS', 'Authenticator (Google ...)', 'Universal'], selected: 1, label: false, input_html: {disabled: 'disabled', value: current_user.two_factor_via} %>
  </div>

  <div class="field">
    <label class="label"><%= t('simple_form.labels.professional_block_account_history.tfa_sms') %></label>

    <%= user_tfa_f.input :phone_number, label: false, input_html: {value: current_user.phone_number} %>
  </div>

<% end %>
<div class="actions">
  <%= f.submit t('Save'), :class => 'button is-primary' %>
  <%= link_to professional_dashboard_path, :class => "button is-default" do %>
    <%= t('cancel') %>
  <% end %>
</div>

<% end %>

app/views/professional/profile/_specialities.html.erb
<%= simple_form_for(@doctor_profile, url: {action: @tab}) do |f| %>
  <% @doctor_profile.specialities.each do |e| %>
    <div>
      <%= e.speciality.en_fr %>
    </div>
  <% end %>
  <small class="is-warning"> Attention, vous allez annuler tous vos rendez vous associés avec cette spec</small>

  <div class="">* Ctrl</div>
  <div class="container-fluid">
    <div class="field-body">
      <div class="field">

        <div class="select">

          <%= f.select :speciality_ids,
                       Speciality.all.collect {|p| [p.en_fr, p.id]},
                       {:prompt => t("Please select")},
                       {:multiple => true, :class => 'is-multiple'} %>
        </div>
      </div>
    </div>
  </div>
  <%= f.submit t('submit'), :type => 'submit', :class => 'button medium' %>
<% end %>

app/views/professional/profile/_tabs.html.erb
<h1 class="title is-4">Edit profile</h1>
<div class="tabs">
  <ul>
    <li class="<%= get_tab_active_class(@tab == 'info'  || @tab == 'index' || @tab.nil?) %> %>">
      <%= link_to(professional_profile_path(tab: 'info')) do %>
        <%= t('info') %>
      <% end %>
    </li>
    <li class="<%= get_tab_active_class(@tab == 'address') %> %>">
      <%= link_to(professional_profile_path(tab: 'address')) do %>
        <%= t('address') %>
      <% end %>
    </li>
    <li class="<%= get_tab_active_class(@tab == 'specialities') %> %>">
      <%= link_to(professional_profile_path(tab: 'specialities')) do %>
        <%= t('Specialities & Curriculum') %>
      <% end %>
    </li>

    <li class="<%= get_tab_active_class(@tab == 'documents') %> %>">
      <%= link_to(professional_profile_path(tab: 'documents')) do %>
        <%= t('documents') %>
      <% end %>
    </li>
    <li class="<%= get_tab_active_class(@tab == 'security') %> %>">
      <%= link_to(professional_profile_path(tab: 'security')) do %>
        <%= t('Two factor authentification') %>
      <% end %>
    </li>
    <li class="<%= get_tab_active_class(@tab == 'account') %> %>">
      <%= link_to(professional_profile_path(tab: 'account')) do %>
        <%= t('nav.account') %>
      <% end %>
    </li>
  </ul>
</div>

app/views/professional/profile/confirm_profile.html.erb
<div class="container-fluid">

  <%= t("Document are required for you request, please provide us your job certification so we can verify ") %>
  <!-- /box_general-->
  <%= form_for @doctor_profile, url: {action: "confirm_profile_request"}, :html => {method: "post"} do |f| %>
    <div class="box_general padding_bottom">
      <div class="header_box version_2">
        <h2><i class="fa fa-file-text"></i>Documents</h2>
      </div>
      <div>

        <%= t('Keep hold in \'Ctrl\' to select multiple specialities') %>
        <%= f.select :speciality_ids,
                     Speciality.all.collect {|p| [p.en_fr, p.id]},
                     {:prompt => t("Please select")},
                     {:multiple => true} %>

      </div>
      <!-- /row-->
      <div class="row">
        <%= f.file_field :files, multiple: true %>
      </div>
      <!-- /row-->
    </div>
    <p>
      <%= f.submit t('form.upload'), :type => 'submit', :class => 'btn_1 medium' %>
    </p>

  <% end %>

</div>

app/views/professional/profile/index.html.erb
<%= render 'professional/profile/tabs' %>

<div class="container-fluid">
  <!-- Breadcrumbs-->
    <%= render :partial => "professional/profile/#{@tab}" %>
    <br/>

</div>